version: "3.8"

services:
  server:
    build: ./server
    container_name: tyre_server
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - tyre_network

  client:
    build: ./client
    container_name: tyre_client
    restart: always
    environment:
      - REACT_APP_API_URL=http://tyre_server:3001
    depends_on:
      - server
    networks:
      - tyre_network

  admin:
    build: ./admin
    container_name: tyre_admin
    restart: always
    environment:
      - REACT_APP_API_URL=http://tyre_server:3001
    depends_on:
      - server
    networks:
      - tyre_network

  nginx:
    image: nginx:latest
    container_name: tyre_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/client.conf:ro # Конфиг для client
      - ./admin/nginx.conf:/etc/nginx/conf.d/admin.conf:ro # Конфиг для admin
      - ./client/build:/usr/share/nginx/html # Путь для файлов фронта
      - ./admin/build:/usr/share/nginx/html
    depends_on:
      - client
      - admin
      - server
    networks:
      - tyre_network

  mongo:
    image: mongo:latest
    container_name: tyre_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - tyre_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tyre_network:

volumes:
  mongo_data:
