version: "3.8"

services:
  server:
    build: ./server
    container_name: tyre_server
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - tyre_network

  client:
    build:
      context: ./client
      args:
        REACT_APP_API_URL: "http://tyre_server:3001"
    container_name: tyre_client
    restart: always
    depends_on:
      - server
    networks:
      - tyre_network

  admin:
    build:
      context: ./admin
      args:
        REACT_APP_API_URL: "http://tyre_server:3001"
    container_name: tyre_admin
    restart: always
    depends_on:
      - server
    networks:
      - tyre_network

  nginx:
    image: nginx:latest
    container_name: tyre_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/build:/usr/share/nginx/html/client
      - ./admin/build:/usr/share/nginx/html/admin
    depends_on:
      - client
      - admin
      - server
    networks:
      - tyre_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 3
      timeout: 10s

  mongo:
    image: mongo:latest
    container_name: tyre_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - tyre_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tyre_network:

volumes:
  mongo_data:
