export const ACCUMULATORS = [
  {
    id: 44,
    brand: "TOPLA",
    width: 175,
    height: 276,
    length: 276,
    model: "Energy 630 En",
    polarity: "Обратная",
    capacity: "73",
    price: 9500,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 45,
    brand: "TOPLA",
    width: 175,
    height: 225,
    length: 232,
    model: "Top JIS 600 En",
    polarity: "Обратная",
    capacity: "60",
    price: 9500,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 46,
    brand: "TOPLA",
    size: "242х175х175",
    width: 175,
    height: 175,
    length: 242,
    model: "Top 600 En",
    polarity: "Обратная",
    capacity: "62",
    price: 9590,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 47,
    brand: "TOPLA",
    width: 175,
    height: 190,
    length: 242,
    model: "Energy 620 En",
    polarity: "Обратная",
    capacity: "66",
    price: 9590,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 48,
    brand: "TAXXON",
    width: 175,
    height: 190,
    length: 207,
    model: "DRIVE EURO 470 En",
    polarity: "Обратная",
    capacity: "50",
    price: 6250,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 49,
    brand: "VARTA",
    width: 175,
    height: 175,
    length: 242,
    model: "BDn 540 En",
    polarity: "Обратная",
    capacity: "60",
    price: 11200,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 50,
    brand: "VARTA",
    width: 175,
    height: 175,
    length: 276,
    model: "BDn 680 En",
    polarity: "Обратная",
    capacity: "72",
    price: 11200,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 51,
    brand: "VARTA",
    width: 175,
    height: 225,
    length: 232,
    model: "Standart 520 En",
    polarity: "Обратная",
    capacity: "60",
    price: 8350,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 52,
    brand: "VARTA",
    width: 175,
    height: 190,
    length: 242,
    model: "BDn 540 En",
    polarity: "Обратная",
    capacity: "60",
    price: 10950,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 53,
    brand: "VST",
    width: 175,
    height: 190,
    length: 242,
    model: "L2-1 540 En",
    polarity: "Обратная",
    capacity: "60",
    price: 5950,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 54,
    brand: "VST",
    width: 175,
    height: 190,
    length: 242,
    model: "EFB 600 En",
    polarity: "Обратная",
    capacity: "60",
    price: 8800,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 55,
    brand: "VST",
    width: 175,
    height: 225,
    length: 260,
    model: "D26-3 680 En",
    polarity: "Обратная",
    capacity: "75",
    price: 9500,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 56,
    brand: "VST",
    width: 175,
    height: 190,
    length: 353,
    model: "L5-1 820 En",
    polarity: "Обратная",
    capacity: "100",
    price: 11800,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 57,
    brand: "TAXXON",
    width: 175,
    height: 190,
    length: 242,
    model: "DRIVE EURO 550 En",
    polarity: "Обратная",
    capacity: "60",
    price: 5750,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 58,
    brand: "TAXXON",
    width: 175,
    height: 190,
    length: 242,
    model: "DRIVE EURO 600 En",
    polarity: "Прямая",
    capacity: "62",
    price: 5850,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 59,
    brand: "TAXXON",
    width: 127,
    height: 225,
    length: 187,
    model: "DRIVE ASIA 310 En",
    polarity: "Прямая",
    capacity: "40",
    price: 4450,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 60,
    brand: "VARTA",
    width: 175,
    height: 225,
    length: 306,
    model: "BDn 830 En",
    polarity: "Прямая",
    capacity: "95",
    price: 15950,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 61,
    brand: "VST",
    width: 175,
    height: 190,
    length: 242,
    model: "L2R-1 540 En",
    polarity: "Прямая",
    capacity: "60",
    price: 5950,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 62,
    brand: "VST",
    width: 175,
    height: 190,
    length: 276,
    model: "L3R-1 680 En",
    polarity: "Прямая",
    capacity: "74",
    price: 8900,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 63,
    brand: "СОЮЗ (Turkey)",
    width: 175,
    height: 190,
    length: 242,
    model: "6 СТ 500 En",
    polarity: "Прямая",
    capacity: "60",
    price: 3990,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 64,
    brand: "ТИТАН",
    width: 175,
    height: 225,
    length: 306,
    model: "ASIA EFB 6СТ 850 En",
    polarity: "Прямая",
    capacity: "100",
    price: 13250,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 65,
    brand: "MUTLU",
    width: 175,
    height: 190,
    length: 242,
    model: "SFB M3 540 En",
    polarity: "Прямая",
    capacity: "60",
    price: 9950,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 66,
    brand: "КАТОД",
    width: 175,
    height: 190,
    length: 242,
    model: "6СТ 540 En",
    polarity: "Прямая",
    capacity: "60",
    price: 5550,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 67,
    brand: "КАТОД",
    width: 175,
    height: 190,
    length: 242,
    model: "6СТ 580 En",
    polarity: "Прямая",
    capacity: "62",
    price: 5650,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 68,
    brand: "КАТОД",
    width: 175,
    height: 190,
    length: 276,
    model: "6СТ 680 En",
    polarity: "Прямая",
    capacity: "75",
    price: 6500,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 69,
    brand: "HITEC",
    width: 175,
    height: 190,
    length: 276,
    model: "Superior Reliability 690 En",
    polarity: "Прямая",
    capacity: "77",
    price: 9120,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 70,
    brand: "HITEC",
    width: 175,
    height: 225,
    length: 276,
    model: "ASIA 640 En",
    polarity: "Прямая",
    capacity: "80",
    price: 8330,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 71,
    brand: "Eurostart",
    width: 175,
    height: 225,
    length: 306,
    model: "6 СТ 700 En",
    polarity: "Прямая",
    capacity: "90",
    price: 9950,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 72,
    brand: "NORD",
    width: 61,
    height: 131,
    length: 136,
    model: "Light",
    polarity: "Прямая",
    capacity: "5",
    price: 600,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 73,
    brand: "HYUNDAI",
    width: 175,
    height: 190,
    length: 242,
    model: "Bolt 590 En",
    polarity: "Прямая",
    capacity: "60",
    price: 5900,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 74,
    brand: "HYUNDAI",
    width: 175,
    height: 190,
    length: 242,
    model: "Bolt 590 En",
    polarity: "Прямая",
    capacity: "60",
    price: 5900,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 75,
    brand: "EXIDE",
    width: 175,
    height: 225,
    length: 232,
    model: "Premium 580 En",
    polarity: "Обратная",
    capacity: "65",
    price: 12500,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 76,
    brand: "ТИТАН",
    width: 175,
    height: 175,
    length: 242,
    model: "EURO Silver 600 En",
    polarity: "Обратная",
    capacity: "60",
    price: 8950,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 77,
    brand: "ТИТАН",
    width: 175,
    height: 190,
    length: 353,
    model: "EFB 6СТ 930 En",
    polarity: "Обратная",
    capacity: "100",
    price: 14250,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 78,
    brand: "ТИТАН",
    width: 175,
    height: 225,
    length: 260,
    model: "ASIA EFB 6СТ 710 En",
    polarity: "Обратная",
    capacity: "80",
    price: 10850,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 79,
    brand: "MUTLU",
    width: 175,
    height: 225,
    length: 232,
    model: "SFB M2 520 En",
    polarity: "Обратная",
    capacity: "60",
    price: 9430,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 80,
    brand: "MUTLU",
    width: 175,
    height: 175,
    length: 242,
    model: "SFB M3 540 En",
    polarity: "Обратная",
    capacity: "60",
    price: 9100,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 81,
    brand: "ZUBR",
    width: 175,
    height: 190,
    length: 207,
    model: "Ultra 440 En",
    polarity: "Обратная",
    capacity: "50",
    price: 6100,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
  {
    id: 82,
    brand: "ZUBR",
    width: 127,
    height: 225,
    length: 187,
    model: "PREMIUM ASIA 300 En",
    polarity: "Обратная",
    capacity: "40",
    price: 5950,
    imgSrc:
      "https://pngimg.com/uploads/automotive_battery/automotive_battery_PNG12100.png",
  },
];
