export const DISKS = [
  {
    id: 1,
    type: "alloy",
    brand: "Xtrike",
    model: "103",
    diametr: "14",
    mount: "4*98",
    width: "-",
    color: "HSB",
    price: 4400,
  },
  {
    id: 2,
    type: "alloy",
    brand: "Xtrike",
    model: "104",
    diametr: "14",
    mount: "4*98",
    width: "-",
    color: "HSB",
    price: 4400,
  },
  {
    id: 3,
    type: "alloy",
    brand: "Xtrike",
    model: "103",
    diametr: "14",
    mount: "4*98",
    width: "-",
    color: "HS",
    price: 4400,
  },
  {
    id: 4,
    type: "alloy",
    brand: "Xtrike",
    model: "114",
    diametr: "14",
    mount: "4*98",
    width: "-",
    color: "HS",
    price: 4400,
  },
  {
    id: 5,
    type: "stamp",
    brand: "ГАЗ",
    model: "-",
    diametr: "13",
    mount: "4*98",
    width: "5",
    offset: "29",
    hole: "58.6",
    color: "HS",
    price: 900,
  },
  {
    id: 6,
    type: "stamp",
    brand: "ГАЗ",
    model: "-",
    diametr: "13",
    mount: "4*98",
    width: "5",
    offset: "35",
    hole: "58.6",
    color: "HS",
    price: 900,
  },
  {
    id: 7,
    type: "stamp",
    brand: "Trebl",
    model: "-",
    diametr: "13",
    mount: "4*114,3",
    width: "4.5",
    offset: "45",
    hole: "69",
    color: "silver",
    price: 2250,
  },
  {
    id: 8,
    type: "stamp",
    brand: "CT",
    model: "-",
    diametr: "13",
    mount: "4*114,3",
    width: "5",
    offset: "45",
    hole: "69",
    color: "silver",
    price: 1300,
  },
  {
    id: 9,
    type: "stamp",
    brand: "ТЗСК",
    model: "-",
    diametr: "14",
    mount: "4*98",
    width: "5.5",
    offset: "35",
    hole: "58.6",
    color: "black",
    price: 1750,
  },
  {
    id: 10,
    type: "stamp",
    brand: "Trebl",
    model: "-",
    diametr: "14",
    mount: "4*98",
    width: "5.5",
    offset: "35",
    hole: "58.6",
    color: "black",
    price: 1570,
  },
  {
    id: 11,
    type: "stamp",
    brand: "CT",
    model: "-",
    diametr: "14",
    mount: "4*98",
    width: "5.5",
    offset: "44",
    hole: "58.1",
    color: "silver",
    price: 1500,
  },
  {
    id: 12,
    type: "stamp",
    brand: "CT",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5.5",
    offset: "45",
    hole: "56.1",
    color: "silver",
    price: 2200,
  },
  {
    id: 13,
    type: "stamp",
    brand: "Trebl",
    model: "5220",
    diametr: "14",
    mount: "4*100",
    width: "5",
    offset: "46",
    hole: "54.1",
    color: "black",
    price: 1450,
  },
  {
    id: 14,
    type: "stamp",
    brand: "Trebl",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "45",
    hole: "54.1",
    color: "black",
    price: 1500,
  },
  {
    id: 15,
    type: "stamp",
    brand: "CT",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "45",
    hole: "54.1",
    color: "silver",
    price: 1450,
  },
  {
    id: 16,
    type: "stamp",
    brand: "CT",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "46",
    hole: "54.1",
    color: "silver",
    price: 1400,
  },
  {
    id: 17,
    type: "stamp",
    brand: "CT",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "49",
    hole: "56.6",
    color: "silver",
    price: 1400,
  },
  {
    id: 17,
    type: "stamp",
    brand: "Trebl",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "49",
    hole: "56.6",
    color: "black",
    price: 2200,
  },
  {
    id: 18,
    type: "stamp",
    brand: "Trebl",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "49",
    hole: "56.6",
    color: "silver",
    price: 1400,
  },
  {
    id: 19,
    type: "stamp",
    brand: "Trebl",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "35",
    hole: "57",
    color: "black",
    price: 2200,
  },
  {
    id: 20,
    type: "stamp",
    brand: "CT",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "45",
    hole: "57",
    color: "black",
    price: 2200,
  },
  {
    id: 21,
    type: "stamp",
    brand: "CT",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "36",
    hole: "60.1",
    color: "silver",
    price: 2200,
  },
  {
    id: 22,
    type: "stamp",
    brand: "Trebl",
    model: "53A36C",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "36",
    hole: "60.1",
    color: "black",
    price: 2200,
  },
  {
    id: 23,
    type: "stamp",
    brand: "Trebl",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "43",
    hole: "60.1",
    color: "black",
    price: 1450,
  },
  {
    id: 24,
    type: "stamp",
    brand: "CT",
    model: "-",
    diametr: "14",
    mount: "4*100",
    width: "5,5",
    offset: "43",
    hole: "60.1",
    color: "silver",
    price: 2200,
  },
  {
    id: 25,
    type: "stamp",
    brand: "Ford",
    model: "-",
    diametr: "14",
    mount: "4*108",
    width: "5,5",
    offset: "37.5",
    hole: "63.3",
    color: "black",
    price: 1750,
  },
  {
    id: 25,
    type: "stamp",
    brand: "CT",
    model: "-",
    diametr: "14",
    mount: "4*108",
    width: "5,5",
    offset: "47",
    hole: "63.3",
    color: "silver",
    price: 2400,
  },
];
