export const TYRES = [
  {
    id: 1,
    season: "winter",
    brand: "Bel",
    model: "367",
    width: "185",
    radius: "15",
    height: "60",
    price: 3900,
    count: 9,
  },
  {
    id: 2,
    season: "winter",
    brand: "Toyo",
    model: "GSI",
    width: "185",
    radius: "15",
    height: "60",
    price: 4900,
    count: 6,
  },
  {
    id: 3,
    season: "winter",
    brand: "Nokia",
    model: "NORDMAN",
    width: "185",
    radius: "15",
    height: "60",
    price: 5262,
    count: 10,
  },
  {
    id: 4,
    season: "winter",
    brand: "Bel",
    model: "287",
    width: "185",
    radius: "15",
    height: "65",
    price: 4100,
    count: 11,
  },
  {
    id: 5,
    season: "winter",
    brand: "Kumho",
    model: "WI",
    width: "185",
    radius: "15",
    height: "65",
    price: 4227,
    count: 9,
  },
  {
    id: 6,
    season: "winter",
    brand: "Toyo",
    model: "GSI",
    width: "185",
    radius: "15",
    height: "65",
    price: 4170,
    count: 4,
  },
  {
    id: 7,
    season: "winter",
    brand: "Yokohama",
    model: "ICE GUARD IG",
    width: "185",
    radius: "15",
    height: "65",
    price: 4293,
    count: 4,
  },
  {
    id: 8,
    season: "winter",
    brand: "Viatti",
    model: "Brina V",
    width: "185",
    radius: "15",
    height: "65",
    price: 2769,
    count: 5,
  },
  {
    id: 9,
    season: "winter",
    brand: "Nitto",
    model: "NTSPK",
    width: "185",
    radius: "15",
    height: "65",
    price: 4499,
    count: 7,
  },
  {
    id: 10,
    season: "summer",
    brand: "Bel",
    model: "286",
    width: "185",
    radius: "15",
    height: "60",
    price: 4200,
    count: 9,
  },
  {
    id: 11,
    season: "summer",
    brand: "Matador",
    model: "MP 47",
    width: "185",
    radius: "15",
    height: "60",
    price: 4800,
    count: 9,
  },
  {
    id: 12,
    season: "summer",
    brand: "Bel",
    model: "280",
    width: "185",
    radius: "15",
    height: "60",
    price: 4375,
    count: 9,
  },
  {
    id: 13,
    season: "summer",
    brand: "Nexen",
    model: "Nferra SU 4",
    width: "185",
    radius: "15",
    height: "65",
    price: 5000,
    count: 9,
  },
  {
    id: 14,
    season: "summer",
    brand: "Kumho",
    model: "KH 27",
    width: "185",
    radius: "15",
    height: "65",
    price: 4650,
    count: 9,
  },
  {
    id: 15,
    season: "summer",
    brand: "Aosen",
    model: "HH 301",
    width: "185",
    radius: "15",
    height: "65",
    price: 4325,
    count: 9,
  },
  {
    id: 16,
    season: "summer",
    brand: "Pirelli",
    model: "F Energy 88 Т",
    width: "185",
    radius: "15",
    height: "65",
    price: 4600,
    count: 9,
  },
  {
    id: 17,
    season: "summer",
    brand: "Dunlop",
    model: "R1",
    width: "185",
    radius: "15",
    height: "65",
    price: 5400,
    count: 9,
  },
];
