export const WINTER_TYRES = [
  {
    id: 1,
    brand: "Bel",
    models: "367",
    width: "185",
    radius: "15",
    height: "60",
    isWinter: true,
    price: 3900,
    count: 9,
  },
  {
    id: 2,
    brand: "Toyo",
    models: "GSI",
    width: "185",
    radius: "15",
    height: "60",
    isWinter: true,
    price: 4900,
    count: 6,
  },
  {
    id: 3,
    brand: "Nokia",
    models: "NORDMAN",
    width: "185",
    radius: "15",
    height: "60",
    isWinter: true,
    price: 5262,
    count: 10,
  },
  {
    id: 4,
    brand: "Bel",
    models: "287",
    width: "185",
    radius: "15",
    height: "65",
    isWinter: true,
    price: 4100,
    count: 11,
  },
  {
    id: 5,
    brand: "Kumho",
    models: "WI",
    width: "185",
    radius: "15",
    height: "65",
    isWinter: true,
    price: 4227,
    count: 9,
  },
  {
    id: 6,
    brand: "Toyo",
    models: "GSI",
    width: "185",
    radius: "15",
    height: "65",
    isWinter: true,
    price: 4170,
    count: 4,
  },
  {
    id: 7,
    brand: "Yokohama",
    models: "ICE GUARD IG",
    width: "185",
    radius: "15",
    height: "65",
    isWinter: true,
    price: 4293,
    count: 4,
  },
  {
    id: 8,
    brand: "Viatti",
    models: "Brina V",
    width: "185",
    radius: "15",
    height: "65",
    isWinter: true,
    price: 2769,
    count: 5,
  },
  {
    id: 9,
    brand: "Nitto",
    models: "NTSPK",
    width: "185",
    radius: "15",
    height: "65",
    isWinter: true,
    price: 4499,
    count: 7,
  },
];
