import { ACCUMULATOR_ACTIONS } from "../../../store_const";

export const CHANGE_ACCUMULATORS_BY_PARAMS_TRUE = {
  type: ACCUMULATOR_ACTIONS.CHANGE_ACCUMULATORS_IS_BY_PARAMS_TRUE,
};

export const CHANGE_ACCUMULATORS_BY_PARAMS_FALSE = {
  type: ACCUMULATOR_ACTIONS.CHANGE_ACCUMULATORS_IS_BY_PARAMS_FALSE,
};
