export const CHANGE_ACCUMULATORS_BY_PARAMS_TRUE = {
  type: "CHANGE_ACCUMULATORS_IS_BY_PARAMS_TRUE",
};

export const CHANGE_ACCUMULATORS_BY_PARAMS_FALSE = {
  type: "CHANGE_ACCUMULATORS_IS_BY_PARAMS_FALSE",
};
