export const MAIN_ACTIONS = {
  CHANGE_IS_ERROR: "CHANGE_IS_ERROR",
  CHANGE_LOADING_IS_FALSE: "CHANGE_LOADING_IS_FALSE",
  CHANGE_LOADING_IS_TRUE: "CHANGE_LOADING_IS_TRUE",
  OPEN_CART_MODAL: "OPEN_CART_MODAL",
  CLOSE_CART_MODAL: "CLOSE_CART_MODAL",
};

export const CART_ACTIONS = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
};
