import { TYRE_ACTIONS } from "../../../store_const";

export const CHANGE_TYRES_BY_PARAMS_TRUE = {
  type: TYRE_ACTIONS.CHANGE_TYRES_BY_PARAMS_TRUE,
};

export const CHANGE_TYRES_BY_PARAMS_FALSE = {
  type: TYRE_ACTIONS.CHANGE_TYRES_BY_PARAMS_FALSE,
};
