name: Docker Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Кешируем зависимости для server
      - name: Cache server dependencies
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-

      # 3. Кешируем зависимости для client
      - name: Cache client dependencies
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: ${{ runner.os }}-client-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-client-

      # 4. Кешируем зависимости для admin
      - name: Cache admin dependencies
        uses: actions/cache@v3
        with:
          path: admin/node_modules
          key: ${{ runner.os }}-admin-${{ hashFiles('admin/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-admin-

      # 5. Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build & push server
      - name: Build and push server image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL="http://" \
            -t redavillm/tyre_server:latest ./server
          docker push redavillm/tyre_server:latest

      # 7. Build & push client
      - name: Build and push client image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL="https://tyreshop-dev.tw1.ru/api" \
            -t redavillm/tyre_client:latest ./client
          docker push redavillm/tyre_client:latest

      # 8. Build & push admin
      - name: Build and push admin image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL="https://tyreshop-admin-dev.tw1.ru/api" \
            -t redavillm/tyre_admin:latest ./admin
          docker push redavillm/tyre_admin:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to server and update containers
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          # при желании можно увеличить таймаут (в секундах):
          timeout: 1800
          script: |
            echo "Переходим в директорию /home/tyre_shop..."
            cd /home/tyre_shop || exit 1

            echo "Загружаем новые образы..."
            docker pull redavillm/tyre_server:latest
            docker pull redavillm/tyre_client:latest
            docker pull redavillm/tyre_admin:latest

            echo "Перезапускаем контейнеры..."
            docker-compose down || true
            docker-compose up -d
