name: Docker Build and Deploy

on:
  push:
    branches:
      - main # или другая ветка для деплоя
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Собираем Docker образы и Публикуем образы на Docker Hub
      - name: Build and push server image
        run: |
          docker build -t yourusername/tyre_server:latest ./server
          docker push yourusername/tyre_server:latest
      - name: Build and push client image
        run: |
          docker build -t yourusername/tyre_client:latest ./client
          docker push yourusername/tyre_client:latest
      - name: Build and push admin image
        run: |
          docker build -t yourusername/tyre_admin:latest ./admin
          docker push yourusername/tyre_admin:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Шаг 1: SSH на сервер
      - name: SSH to server and update containers
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            docker pull yourusername/tyre_server:latest
            docker pull yourusername/tyre_client:latest
            docker pull yourusername/tyre_admin:latest

            docker-compose down
            docker-compose up -d --build
