name: Docker Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Собираем Docker образы и пушим их в Docker Hub
      - name: Build and push images
        run: |
          docker build -t redavillm/tyre_server:latest ./server
          docker push redavillm/tyre_server:latest

          docker build -t redavillm/tyre_client:latest ./client
          docker push redavillm/tyre_client:latest

          docker build -t redavillm/tyre_admin:latest ./admin
          docker push redavillm/tyre_admin:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to server and update containers
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Переходим в директорию с docker-compose.yml на сервере
            echo "Переходим в директорию /opt/tyre_shop_project..."
            cd /opt/tyre_shop_project || exit 1

            # Выводим список файлов для проверки, что docker-compose.yml присутствует
            echo "Список файлов в /opt/tyre_shop_project:"
            ls -l /opt/tyre_shop_project

            # Останавливаем текущие контейнеры
            echo "Останавливаем контейнеры..."
            docker-compose down || true

            # Подтягиваем обновленные образы с Docker Hub
            echo "Загружаем обновленные образы..."
            docker pull redavillm/tyre_server:latest
            docker pull redavillm/tyre_client:latest
            docker pull redavillm/tyre_admin:latest

            # Запускаем контейнеры через docker-compose (используя уже существующий docker-compose.yml)
            echo "Запускаем контейнеры..."
            docker-compose up -d --build
