name: Docker Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Собираем Docker образы и пушим их в Docker Hub
      - name: Build and push images
        run: |
          docker build --build-arg REACT_APP_API_URL="http://" -t redavillm/tyre_server:latest ./server
          docker push redavillm/tyre_server:latest

          docker build --build-arg REACT_APP_API_URL="https://tyreshop-dev.tw1.ru/api" -t redavillm/tyre_client:latest ./client
          docker push redavillm/tyre_client:latest

          docker build --build-arg REACT_APP_API_URL="https://tyreshop-admin-dev.tw1.ru/api" -t redavillm/tyre_admin:latest ./admin
          docker push redavillm/tyre_admin:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to server and update containers
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "Переходим в директорию /home/tyre_shop..."
            cd /home/tyre_shop || exit 1

            # Загружаем обновленные образы с Docker Hub
            echo "Загружаем обновленные образы..."
            docker pull redavillm/tyre_server:latest
            docker pull redavillm/tyre_client:latest
            docker pull redavillm/tyre_admin:latest

            # Останавливаем старые контейнеры
            echo "Останавливаем контейнеры..."
            docker-compose down || true

            # Запускаем контейнеры через docker-compose
            echo "Запускаем контейнеры..."
            docker-compose up -d --build
