name: Docker Build and Deploy

on:
  push:
    branches:
      - master # или другая ветка для деплоя
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Собираем Docker образы и Публикуем образы на Docker Hub
      - name: Build and push server image
        run: |
          docker build -t redavillm/tyre_server:latest ./server
          docker push redavillm/tyre_server:latest
      - name: Build and push client image
        run: |
          docker build -t redavillm/tyre_client:latest ./client
          docker push redavillm/tyre_client:latest
      - name: Build and push admin image
        run: |
          docker build -t redavillm/tyre_admin:latest ./admin
          docker push redavillm/tyre_admin:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Шаг 1: SSH на сервер
      - name: SSH to server and update containers
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /opt/tyre_shop_project || exit 1

            docker rm -f tyre_server tyre_client tyre_admin || true

            docker system prune -f || true

            docker pull redavillm/tyre_server:latest
            docker pull redavillm/tyre_client:latest
            docker pull redavillm/tyre_admin:latest

            echo "
            version: '3'
            services:
              tyre_server:
                image: redavillm/tyre_server:latest
                container_name: tyre_server
                restart: always
              tyre_client:
                image: redavillm/tyre_client:latest
                container_name: tyre_client
                restart: always
              tyre_admin:
                image: redavillm/tyre_admin:latest
                container_name: tyre_admin
                restart: always
            " > docker-compose.yml

            docker-compose down || true

            docker-compose up -d --build
